#image: python:3.7
#
#test:
#    script:
#        python3 app/__init__.py
#        python3 app/api.py
#        python3 app/calculator.py
#        python3 app/period.py
#        python3 app/validation.py
#        python3 test/pyunittest.py

    stages:
        - build
        - test

    build:
        stage: build
        tags:
            - fit2107-runner
        image: python:3.8-alpine
        script:
            python3 app/__init__.py
            python3 app/api.py
            python3 app/calculator.py
            python3 app/period.py
            python3 app/validation.py
    test:
        stage: test
        image: python:3.8-alpine
        script:
            python3 test/pyunittest.py